/*
 * This source file was generated by the Gradle 'init' task
 */
package com.craftinginterpreters.lox;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class Lox {
    public static final int MIN_ARGS = 1;
    
    static boolean hadError = false; // ensures we don't execute code that has
                                     // a known error

    public static void usage() {
        System.out.println("Usage: jlox [script]");
    }

    public static void main(String[] args) {
        if (args.length < MIN_ARGS) {
            usage();
            System.exit(SysError.EX_USAGE.value());
        } else if (args.length == 1) {
            runFile(args[0]);
        } else {
            runPrompt();
        }
    }

    private static void runFile(String path) throws IOException {
        byte[] bytes = Files.readAllBytes(Paths.get(path));
        run(new String(bytes, Charset.defaultCharset()));

        if (hadError) { System.exit(SysError.EX_DATAERR.value()); }
    }

    private static void runPrompt() throws IOException {
        InputStreamReader input = new InputStreamReader(System.in);
        BufferedReader reader = new BufferedReader(input);

        for(;;) {
            System.out.println("> ");
            String line = reader.readLine();
            if (line == null) break; // ctrl-d escape code
            run(line);
            hadError = false;
        }
    }

    private static void run(String source) {
        Scanner scanner = new Scanner(source);
        List<Token> tokens = scanner.scanTokens();

        for(Token token : tokens){
            System.out.println(token);
        }
    }

    static void error(int line, String message){
        report(line, "", message);
    }

    private static void report(int line, String where, String message){
        System.err.println(
                "[line " + line + "] Error" + where + ": " + message
                );
        hadError = true;
    }
}
