/*
 * This source file was generated by the Gradle 'init' task
 */
package jlox.cli;

public class jloxMain {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new jloxMain().getGreeting());
    }
}
